### ISSUE TITLE
assigned_basis.txt

### ISSUE THREAD

**Issue by adrybakov** [mailhexu/TB2J#24]
In every run of wann2J.py a file "assigned_basis.txt" is created outside of the TB2J_results directory (in the directory of the script`s execution to be exact). It comes from the function [``auto_assign_basis_name()``](https://github.com/mailhexu/TB2J/blob/955518eecfd6246dc03d8449e8c52b288cf9d374/TB2J/utils.py#L134) defined in utils.py.

I tracked down calls of this function and it is called in several places, in particular:
[manager.py (1)](https://github.com/mailhexu/TB2J/blob/9b1d6de66eb6f42bd158aaba14d211e77bb3046e/TB2J/manager.py#L73)
[manager.py (2)](https://github.com/mailhexu/TB2J/blob/9b1d6de66eb6f42bd158aaba14d211e77bb3046e/TB2J/manager.py#L86)
[manager.py (3)](https://github.com/mailhexu/TB2J/blob/9b1d6de66eb6f42bd158aaba14d211e77bb3046e/TB2J/manager.py#L157)
[manager.py (4)](https://github.com/mailhexu/TB2J/blob/9b1d6de66eb6f42bd158aaba14d211e77bb3046e/TB2J/manager.py#L201)
[manager.py (5)](https://github.com/mailhexu/TB2J/blob/9b1d6de66eb6f42bd158aaba14d211e77bb3046e/TB2J/manager.py#L389)
[Oiju.py](https://github.com/mailhexu/TB2J/blob/955518eecfd6246dc03d8449e8c52b288cf9d374/TB2J/Oiju.py#L79)
[myTB.py](https://github.com/mailhexu/TB2J/blob/96084351517d8767f2cbb1f89e1f6532afc3fcd2/TB2J/myTB.py#L208)
[utest.py](https://github.com/mailhexu/TB2J/blob/955518eecfd6246dc03d8449e8c52b288cf9d374/TB2J/utest.py#L75)

And in every case it seems to me that appearance of the file itself is not desired.

Therefore, since appearance of this file is confusing, I suggest to change the behaviour of the code in that sense.

I see two simple solutions:

* [Solution1](https://github.com/adrybakov/TB2J/tree/solution1) 
    To redefine default value of  [``write_basis_file``](https://github.com/mailhexu/TB2J/blob/955518eecfd6246dc03d8449e8c52b288cf9d374/TB2J/utils.py#L137) from 'assigned_basis.txt' to None, then the file will appear only if it is desired, but not as a side effect.
* [Solution2](https://github.com/adrybakov/TB2J/tree/solution2)
    To make it appear in the TB2J_results directory by changing the function [``auto_assign_basis_name()``](https://github.com/mailhexu/TB2J/blob/955518eecfd6246dc03d8449e8c52b288cf9d374/TB2J/utils.py#L134) and it`s calls in a particular way.

I can open a pull request for either first or second solution, so the question is: which one do you prefer? Or do you plan to address this issue in a different way?

P.S. One more question, which came from this investigation: there is a number of unused imports in the code, do you keep them with a reason, or are they just left there historically?

**Comment by mailhexu** [comment]
Hi, 
Thank you!
Sorry for this very late reply. I don't know why I didn't see this issue. 
Now I moved the assigned_basis.txt to the TB2J output directory instead of the current working directory. (your solution 2). 
Indeed I need to clean the unsued import too. Will do it soon. 
Best wishes,
HeXu

**Comment by adrybakov** [comment]
Hello, 
Thank you!
Best,
Andrey
