### ISSUE TITLE
XYZ posfile

### ISSUE THREAD

**Issue by nicolastd** [mailhexu/TB2J#3]
Dear developers,

It seems that at the moment it is possible to provide an apparently valid --posfile option with an XYZ file (supported by ASE).
However, this leads to a zero Cell parameter matrix, which lead to a singular matrix at some point in the code.

Probably this should be check.

**Comment by mailhexu** [comment]
Thanks!
Indeed xyz format can not be used. In the next version, the posfile option will be removed, instead it will only use the Wannier input and output files to get the position information.
