### ISSUE TITLE
[ENH]: Code style

### ISSUE THREAD

**Issue by adrybakov** [mailhexu/TB2J#34]
Hello!

Is there any code style in TB2J?

If no, then what do you think about adopting [Black](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html)?

Best,
Andrey

**Comment by mailhexu** [comment]
Great idea. Will do it soon. 
Best, 
HeXu

**Comment by adrybakov** [comment]
Great!

Best,
Andrey

**Comment by adrybakov** [comment]
Added in 5ca597afb5ebdf6d565f78db732c518740ded23b.
