### ISSUE TITLE
[BUG] Atoms named not as chemical symbols (ase crash)

### ISSUE THREAD

**Issue by adrybakov** [mailhexu/TB2J#46]
When a wannier90 calculations are done with the atom labels, that are different from the chemical symbols (i.e. Fe1 and not Fe), the wann2J.py crashes. The deep source of the error with code examples is described here:
https://gitlab.com/ase/ase/-/issues/1448

Apparently, ASE does not consider this to be a bug, so I am writing about it here. Unfortunately, I can not share the input and output files at the moment. I may add a toy example this week, if necessary. To reproduce, one should name atoms in .win files as described here.

TB2J version: 0.8.1 and 0.7.7

**Comment by mailhexu** [comment]
Thanks. I will try to fix it.

**Comment by mailhexu** [comment]
Hi, 
Could you send a toy example. I  tried to do a calculation with atom labels but I didn't find how to do that. 
Thanks!
HeXu

**Comment by adrybakov** [comment]
Hello,

Yes, I will do so later this week.

Best,
Andrey

**Comment by adrybakov** [comment]
Hello!

Sorry for the delayed response, here is the example of the bug: https://github.com/adrybakov/TB2J-issue-46

There are two folders one runs perfectly, the other one crashes.

* There is no need to recompute QE and Wannier90 steps - all files necessary for TB2J are present. 
* In "run.sh" file of each folder there are the commands, that I've used. 
* In "run-fail" folder there is a file "TB2J_CRASH" with the Traceback.

Best,
Andrey

**Comment by mailhexu** [comment]
Thanks a lot!
I fixed it in the latest version (0.8.2.3). Could you try with that?
see https://github.com/mailhexu/TB2J/commit/3b923db6ab998fc8ec4ca367f4a4085704cf8b6f 
Best, 
HeXu

**Comment by adrybakov** [comment]
Yes, It works now, thanks!

Best,
Andrey
