### ISSUE TITLE
Truncated line in documentation

### ISSUE THREAD

**Issue by ahkole** [mailhexu/TB2J#48]
https://github.com/mailhexu/TB2J/blob/e3670409a5c65058e4a849228521d53b738142d1/docs/src/parameters.rst?plain=1#L24

One of the sentences in the line above in the documentation is truncated. In particular, it's the following sentence: `It can be used to adjust the integration if the charge .`. What was supposed to be written here?

**Comment by mailhexu** [comment]
Hi,
Thanks! I wanted to write : if we want to simulate some charge doping effect by simply let the electron to occupy some state above the Fermi energy. But eventually, I will remove the emax parameter, as it should be 0 in almost all cases. And even if we want to simulate the doping effect, to do it within the DFT calculation is more accurate.
Best regards, 
HeXu

**Comment by mailhexu** [comment]
Fixed in this commit: https://github.com/mailhexu/TB2J/commit/8f89ce0c5d9fc84c4b3a9b44409ffb0171ebb7d6 .

**Comment by ahkole** [comment]
Thanks for fixing it! I actually found another paragraph in the documentation with some truncated sentences, see here:

https://github.com/mailhexu/TB2J/blob/affdcbe549ef849fb54f238d85fc65e838c2403f/docs/src/downfold.md?plain=1#L3

The first and last sentence of this line are truncated. It would be helpful if these are completed as well.

**Comment by mailhexu** [comment]
Thanks . This is fixed now.
