### ISSUE TITLE
TB2J with vasp

### ISSUE THREAD

**Issue by akentphonon** [mailhexu/TB2J#5]
Dear Developers,

I wanted to know if we can use TB2J with a combination of VASP+Wannier90.

Thanks,

Alex

**Comment by mailhexu** [comment]
Hi Alex,

Yes.

You can find some examples in

https://github.com/mailhexu/TB2J_examples/tree/master/Wannier

Best wishes,

HeXu

**Comment by akentphonon** [comment]
Thanks!!!
