### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by lyonworton** [mailhexu/TB2J#50]
Hello, I would like to know if Jani and DMI are taken into account in the latest version of TB2J when calculating the magnon band structure. When I perform the --no_Jani and --no_dmi operations under the TB2J_magnon.py command after calculating the task with abacus and generating the exchange.xml file with TB2J, I get no change in the magnon band structure. However, when I remove the parts about Jani and DMI from the exchange.xml file, the calculated magnon band structure has changed, I would like to know what is going on and whether these changes are reliable?

**Comment by mailhexu** [comment]
Hello, 
Indeed the --no_jani and --no_dmi is currently broken. We're currently rewriting the magnon code, fixing bugs and  adding more features. Please stay tuned. 
Best regards, 
HeXu

**Comment by lyonworton** [comment]
Thank you, so far I know that the exchange.xml file results are consistent with the exchange.out file, and I was wondering if the current TB2J_magnon.py calculations to get the magnon band structure take Jani and DMI into account？As I noticed that Computer Physics Communications 264 (2021) 107938 mentions that Jani and DMI will be taken into account in later versions.

> Hello, Indeed the --no_jani and --no_dmi is currently broken. We're currently rewriting the magnon code, fixing bugs and adding more features. Please stay tuned. Best regards, HeXu
