### ISSUE TITLE
[Important] Theoretical Discussion

### ISSUE THREAD

**Issue by servant1991** [mailhexu/TB2J#53]
In the example of SrMnO3, if we additionally consider the  Mn-O exchange interaction J in the TB2J software, what is different with the only considered Mn-Mn one. Assuredly, the J between Mn atoms is dominated, while the J between Mn-O is negligible. For most magnetic systems, it is reasonable to only consider the J between magnetic atoms.  In this case, the calculated J between the total energy mapping and magnetic force method are  consistent. However, if the exchange interaction J between the magnetic and ligand  atoms is considerable. Is it credible when we only concern the J between magnetic atoms.

**Comment by mailhexu** [comment]
Hello, 
If the J(metal-ligand) is large, then you can do a downfolding to get an effective J'(metal-metal）, and see how much the difference to the J(metal-metal) without downfolding is, which gives an rough idea on how important it is. 
Best regards, 
HeXu

**Comment by servant1991** [comment]
Dear HeXu:
How to do the downfolding? Can you give me some advice?
Best regards,
K.Sheng

**Comment by mailhexu** [comment]
Hello, 
The procedure for the downfolding can be found here:
https://tb2j.readthedocs.io/en/latest/src/downfold.html
Best regards, 
HeXu
