### ISSUE TITLE
Discussion on the number of magnon bands

### ISSUE THREAD

**Issue by lyonworton** [mailhexu/TB2J#54]
Hello, I would like to ask you a question about a problem when calculating magnon band structure. When I consider Jani and DMI in my calculation, why the number of bands drawn is three times the number of atoms and there are many splits? When Jani and DMI are not considered, the three bands of the same atom have the same value, so there are no splits, but when Jani and DMI are considered, the three values are different, but they are all drawn resulting in many bands, is this reasonable?
[CrI3rotateandmerge.zip](https://github.com/mailhexu/TB2J/files/15495228/CrI3rotateandmerge.zip)

**Comment by mailhexu** [comment]
Hello, 
Without DMI/Jani, the system is isotropic in all the directions, so the bands are degenerate. The DMI/Jani lift the degeneracy and gives more bands. 
Best regards, 
HeXu
