### ISSUE TITLE
The mistake of distinguishing of the orbitals

### ISSUE THREAD

**Issue by summitmoon** [mailhexu/TB2J#62]
Hello,

I have an error in the calculation of J. In my case, I projected five d orbitals for each 3d atom (four magnetic atoms in the unit cell) but in the exchange out, it only lists three orbitals for two atoms and five orbitals for the other magnetic atoms. Thus, the in-plane magnetic coupling is calculated to be zero.

**Comment by mailhexu** [comment]
Can you share the files? 
Best regards, 
HeXu

**Comment by summitmoon** [comment]
Dear Xu,

I have attached the file in TB2J group. Thank you. Regards

Xu He ***@***.***> 于2024年10月23日周三 08:02写道：
