### ISSUE TITLE
Problem in plotting magnon_band.pdf

### ISSUE THREAD

**Issue by kyohn1004** [mailhexu/TB2J#8]
Dear Developers,

Thank you very much for this nice code :-)
Here I have a problem about plotting [magnon_band.pdf] using [TB2J_magnon.py]

Attached is the magnon dispersion of BCC Fe.
When I use [v0.4.4.1], there is no problem.
However, when I use a higher version ([v0.6.0] and [v0.6.1]), the plot looks strange.

Here I used the same [exchange.xml] for the two cases.
The only difference is the effect of [TB2J_magnon.py --qpath GNPGHN] from the different version of TB2J.

Thanks :-)
With best regards,
Kyohoon

[magnon_band_v0.4.4.1.pdf](https://github.com/mailhexu/TB2J/files/6756996/magnon_band_v0.4.4.1.pdf)
[magnon_band_v0.6.0.pdf](https://github.com/mailhexu/TB2J/files/6756998/magnon_band_v0.6.0.pdf)

**Comment by mailhexu** [comment]
Dear Kyohoon,
Thanks for reporting this.
 Indeed a bug has been introduced in the new version ( I merged a unfinished branch by accident). In the version 0.6.3 the old behavior is restored.  Please update to it. 

Best regards,
HeXu

**Comment by kyohn1004** [comment]
Dear HeXu,
Thank you very much for this really quick reply.!
